name:                Agents
version:             0.1.0.0
github:              "JCH97/Agents"
license:             BSD3
author:              "Jose Carlos Hernandez"
maintainer:          "jc1997hdez@gmail.com"
copyright:           "2022 Jose Carlos Hernandez"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Agents#readme>

dependencies:
- base >= 4.7 && < 5
- random

library:
  source-dirs: src
  exposed-modules:
    - Lib
    - Items.Agent
    - Items.Child
    - Items.Corral
    - Items.Dirt
    - Items.Enviroment
    - Items.Obstacle
    - Items.Utils

executables:
  Agents-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Agents

tests:
  Agents-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Agents
